name: OnlyWithdraw
main: me.cable.onlywithdraw.OnlyWithdraw
version: 1.0.0
author: Cable

softdepend:
  - Vault

commands:
  onlywithdraw:
    aliases: ow
    permission: onlywithdraw.command.onlywithdraw
